galera-cluster-nodes:
  hosts:
    one:
      ansible_host: 192.168.1.249
      ansible_user: cloudgenius
    two:
      ansible_host: 192.168.1.250
      ansible_user: cloudgenius
    three:
      ansible_host: 192.168.1.251
      ansible_user: cloudgenius
