version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nilesh
      MONGO_INITDB_ROOT_PASSWORD: A12345

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nilesh
      ME_CONFIG_MONGODB_ADMINPASSWORD: A12345
      ME_CONFIG_MONGODB_URL: mongodb://nilesh:A12345@mongo:27017/
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "nilesh"
      ME_CONFIG_BASICAUTH_PASSWORD: "A12345"
